### PR TITLE
Remove trade now buttons

### PR DESCRIPTION
**Pull request by Jadessu**
### Describe your changes 
Remove trade now buttons on landing page and added it to navbar
_Describe the purpose + content of these changes_
image

### Link the related issue

_Closes #0000_

### Checklist before requesting a review
- [ ] Is this a PR meant for test purposes? If so, please open/change to a draft PR to indicate work in progress/test. 
- [ ] I have performed a self-review of my code.
- [ ] Did you request feedback from another team member prior to merge? 
- [ ] Does my code following the style guide at `docs/CODING-STYLE.md`?

### CODE REVIEW

**Review by c33cheun — CHANGES_REQUESTED** [review]
Where does this change come from? I took a look at figma and didn't see this in the header. If there is an issue for this change that I'm missing let me know.

**Review by benwolski — CHANGES_REQUESTED** [review]
I think Miyu's request was to remove just the two middle Trade Now buttons. It seems all have been removed.
image

**Review by c33cheun — APPROVED** [review]
Looks good, thanks for incorporating Miyu's change!

**Review by benwolski — CHANGES_REQUESTED** [review]
the top of each page appears to be cut off now
image

**Review by benwolski — APPROVED** [review]
looks great! buttons work as expected :)

**Pull request merged**
