### PR TITLE
Sidebar UI

### PR DESCRIPTION
**Pull request by enwong10**
### Describe your changes 
Sidebar UI changes

### Link the related issue
_Closes #2687_

### Checklist before requesting a review
- [x] Is this PR ready for merge? (Please convert to a draft PR otherwise)
- [x] I have performed a self-review of my code.
- [x] Did I request feedback from a team member prior to merge? 
- [x] Does my code following the style guide at `docs/CODING-STYLE.md`?

### CODE REVIEW

**Review by benwolski — CHANGES_REQUESTED** [review]
One of the new requirements in the related ticket seems to have been missed:

- the status of the range positions in their own narrow column with no header

image

**Review by surudhb — APPROVED** [review]
Looks good! 

question for @miyuki-eto and @benwolski, would it be better to put the status column either first or last (instead of in the middle)?

First:
image

Last:
image

Current:
image

**Comment by miyuki-eto** [comment]
this looks good. 

i do think the old icons look better tbh. not a huge deal if its a pain, but ideally we could use the old style. most (besides the limit and range icons i think) come from the lucide icons pack - https://lucide.dev/icons/

re the status first or last. i think it looks better last

**Comment by enwong10** [comment]
Waiting on @miyuki-eto for icons decision

**Review by miyuki-eto — APPROVED** [review]
looks good! reviews and approved

**Pull request merged**
