### PR TITLE
show full addresses in tx details

### PR DESCRIPTION
**Pull request by benwolski**
### Describe your changes 
add logic to display full account and token addresses when space is sufficient in transaction details:

before update:
image

after update:
image

### Link the related issue
_Closes #0000_

### Checklist before requesting a review
- [ ] Is this PR ready for merge? (Please convert to a draft PR otherwise)
- [ ] I have performed a self-review of my code.
- [ ] Did I request feedback from a team member prior to merge? 
- [ ] Does my code following the style guide at `docs/CODING-STYLE.md`?

### Instructions for Reviewer
**Functionalities or workflows that should specifically be tested.**

1.

2.

**Environmental conditions which may result in expected but differential behavior.**

1.

2.

### If relevant, list additional work to complete pre-merge (delete logging, code abstraction, etc)

### CODE REVIEW

**Comment by miyuki-eto** [comment]
can we use monospaced font for these? generally all hex values should be monospaced to avoid confusion

**Comment by benwolski** [comment]
updated to use a monospace font for non-ens addresses.

image

image

**Comment by miyuki-eto** [comment]
reviewed and approved

**Review by miyuki-eto — COMMENTED** [review]
approved

**Review by enwong10 — APPROVED** [review]

**Pull request merged**
