### PR TITLE
Landing changes

### PR DESCRIPTION
**Pull request by Jadessu**
### Describe your changes 
_Describe the purpose + content of these changes_
Over the past few days, there has been a few comments regarding the mobile version of the app.
This PR refactors our landing page on mobile devices for a better user experience.
I put this together after going through a few similar exchanges and seeing what they have.

Uni's mobile: https://app.uniswap.org/#/?intro=true
Dodo's mobile: https://dodoex.io/en

This PR:
image
image
image
image
image
image
image
image

### Link the related issue
_Closes #0000_

### Checklist before requesting a review
- [x] Is this PR ready for merge? (Please convert to a draft PR otherwise)
- [x] I have performed a self-review of my code.
- [x] Did I request feedback from a team member prior to merge? 
- [x] Does my code following the style guide at `docs/CODING-STYLE.md`?

### CODE REVIEW

**Review by surudhb — CHANGES_REQUESTED** [review]
think the package-lock got committed accidentally

**Review by surudhb — COMMENTED** [review]
Overall looks great! 
- `MobileHero` doesn't seem to be used
- There's commented out CSS, empty lines that can be deleted

**Review by surudhb — COMMENTED** [review]
Investor logos
- BlockTower, Jane Street, Circle and Yunt Capital seem to be using lower res images still noticable blurry on mobile. 
- Investor logo sizing could be slightly more consistent for the ones that are just text i.e. Don Sun vs afkbyte vs Pre-Seed

Top Pools
- The top and bottom of the Top Pools section gets slightly cut off on my device (iPhone XS) but I don't think thats too big a deal

**Comment by surudhb** [comment]
- make Deep Diversity Liquidity image bigger
- make Bridge the Gap image bigger
- Total Value Locked, Total Volume, Total Fees containers should have consistent padding above the title and below the stat 
- sometimes inconsistent scrolling after reaching the footer

**Review by miyuki-eto — COMMENTED** [review]
can we move the background images on the 'deep, diversified liquidity', 'bridge the gap', and 'better than cex' sections so they dont obscure the content? can just move them up or down

**Review by surudhb — APPROVED** [review]
Overall looks good! There are screen specific issues (probably endless) but I think they can be addressed in a v2 update to the landing page. Test device here was a iPhone XS on portrait and landscape mode.

image
image

**Review by miyuki-eto — CHANGES_REQUESTED** [review]
a few changes -

1. can we swap the order of the stats and top pools? so the top pools comes first
2. the header for 'investors' and 'pre seed' should be the same. i think the pre seed version looks better

**Comment by Jadessu** [comment]
> 

Hey Miyu, I have a few suggestions regarding the requested changes. In terms of swapping the order of the stats and top pools, we'll need to make some adjustments to ensure everything fits seamlessly. Here are a few options I propose:

1. Limit the top pools on mobile to 2 or 3. After testing it on various devices, 3 seems to work well:

image

2. Alternatively, we can create a simplified version of the cards that occupies less space. However, since our goal is to maintain consistency with the desktop version, I am less inclined towards this option.

3. Another possibility is to remove the stats altogether and keep the hero section identical to the desktop version. It would only display the ambient logo and the "Trade Now" button. Following that, we would showcase the top pools, and then the stats. To avoid it appearing too empty, we could think of adding a tagline or some additional content between the logo and the "Trade Now" button:

image


Regarding the header for 'investors' and 'pre seed', if we change the 'investors' header to match the style of 'pre-seed', it might create inconsistency with the rest of the headers ('Top Pools'). However, we can make all the headers consistent with the one on the desktop version.
image
image

Let me know what you think and if you have any other ideas.

**Comment by miyuki-eto** [comment]
hey @Jadessu 

i think we just go with the 3 top pools cards, seems like the best solution

and if we could make the headers match the ones from the desktop version as you suggested i think that would be best

**Review by benwolski — CHANGES_REQUESTED** [review]
1. the 'ambient' logo and the Top Pools header may be out of alignment
2. the 'Ambient Finance Stats' section is missing a background 'waves' image
3. scrolling behavior and stop position is unpredictable (at least on a pixel phone)
4. 'Don Sun' should be 'Don Ho'
5. The top 3 pools should be ETH-USDC, USDC-DAI, and ETH-WBTC

**Review by benwolski — APPROVED** [review]

**Pull request merged**
