### PR TITLE
Proven develop last changes

### PR DESCRIPTION
**Pull request by zcelbirPlabs**
### Describe your changes 
Chart draw last version
- Fibonacci
- Date and Price Range
- Magnet
- Undo & Redo Buttons
- Delete All
- Scrollable Toolbar
- Drawn Shape Settings Page

### Link the related issue
_Closes #0000_

### Checklist before requesting a review
- [ ] Is this PR ready for merge? (Please convert to a draft PR otherwise)
- [ ] I have performed a self-review of my code.
- [ ] Did I request feedback from a team member prior to the merge? 
- [ ] Does my code following the style guide at `docs/CODING-STYLE.md`?

### Instructions for Reviewer
**Functionalities or workflows that should specifically be tested.**

1.

2.

**Environmental conditions that may result in expected but differential behavior.**

1.

2.

### CODE REVIEW

**Comment by benwolski** [comment]
copying Miyu's feedback to the new PR: 

a few notes -

- remove` all shadow to color selection and tick boxes in tool settings
- tooltip on hover shadow is too strong. decrease opacity and adjust falloff so its more subtle fibonacci
- add background opacity control - like tradingview
- change the labels options buttons to be more like tradingview
- border instead of fill
- add arrow
- also move the Labels word and buttons to the left
- i see it was to line up with the Reverse text but i think its better hard left
- setting the individual color opacity to 0 gives it a transparent black color instead of totally transparent rectangle
- option to turn off border isn't functioning
- line display and options not required

**Comment by benwolski** [comment]
copying Miyu's feedback to the new PR:

a few notes -

- remove` all shadow to color selection and tick boxes in tool settings
- tooltip on hover shadow is too strong. decrease opacity and adjust falloff so its more subtle fibonacci
- add background opacity control - like tradingview
- change the labels options buttons to be more like tradingview
- border instead of fill
- add arrow
- also move the Labels word and buttons to the left
- i see it was to line up with the Reverse text but i think its better hard left
- setting the individual color opacity to 0 gives it a transparent black color instead of totally transparent rectangle
- option to turn off border isn't functioning
- line display and options not required

image

**Review by miyuki-eto — COMMENTED** [review]
can we make it so when i click anywhere on the fibonacci it selects it? currently it only selects if you click the diagonal line

otherwise looks good

**Comment by tncoskun** [comment]
- fibonacci was made selectable from all parts of drawn

other fixed issues :
- fib annotation lines calculation for denom
- floating toolbar dragging for mobile
- when dragging the borders of D&P above the chart the tooltip shifts outside the chart borders on mobile
- slider of Fib Level opacity not able to slide

**Review by benwolski — APPROVED** [review]

**Pull request merged**
