### PR TITLE
Enhancement/transaction confirmation upgrades

### PR DESCRIPTION
**Pull request by enwong10**
### Describe your changes 
Consolidate confirmation modals
Update confirm modals and other transaction action modals to use same submit transaction button. All transactions should now be using this flow

### Link the related issue
_Closes #2685_

### Checklist before requesting a review
- [ ] Is this PR ready for merge? (Please convert to a draft PR otherwise)
- [x] I have performed a self-review of my code.
- [x] Did I request feedback from a team member prior to merge? 
- [x] Does my code following the style guide at `docs/CODING-STYLE.md`?

### CODE REVIEW

**Review by benwolski — CHANGES_REQUESTED** [review]
seems we have a bug causing the swap confirmation modal to revert back from the 'Transaction Submitted' state to the 'Price Updated' state if the pool price changes enough to trigger this warning.

image
image

**Review by benwolski — CHANGES_REQUESTED** [review]
seems the 'Add [ERC-20 token] to MetaMask' button is appearing when the ERC-20 token is token A (sell), rather than token B (buy).

image

**Comment by benwolski** [comment]
also, it appears that the logic to log out the user when the user locks MetaMask is no longer working: 
image

**Comment by benwolski** [comment]
and I think the connect wallet modal may have changed in display more than expected
image

**Review by benwolski — APPROVED** [review]
looks great!

**Comment by miyuki-eto** [comment]
this is looking good, a few notes - 

1. can we change the 'Submit another transaction' text to be white when not hovered
2. can we remove the 'Submit another transaction' button entirely when it appears in the confirmation modal, but leave it when its not in the modal and just in the order input panel (the user can just close the modal to submit another tx)
3. add rounding to the corners of the expanded info section - the part with the view on etherscan button
4. the view on etherscan button has no hover state
5. make the view on etherscan and add X to connected wallet buttons the same size
6. can we add a 'Transaction confirmed' state once the tx has been confirmed on the blockchain? not a huge requirement if its a push, but it might be nice to have it change from 'Transaction submitted' to 'Transaction confirmed' once it goes through

**Pull request merged**
