### PR TITLE
Enhancement/trade table UI

### LINKED ISSUE #2689: [Enhancement]: Trade table UI updates
### Requirements

- there is so much space not used that would be better served for showing more buttons
- i know there are some limitations etc. but i think this could be a bit better
- the timestamp column is almost twice the size it needs to be
- the id and wallet columns are wider than they need to be
- the side and type columns are too wide etc
- i also have a icon based button mock up to discuss
- rename the ranges tab to ‘Liquidity’
- on the ranges tab the status of ambient positions doesnt line up with the other ones

### Figma

_No response_

### Assumptions

_No response_

### PR DESCRIPTION
**Pull request by mishaHype**
### Describe your changes 
Tables now use CSS definable size cells. Ranges and Leaderboard now have split CSS for defining table sizes for more finetuning. 
Transactions, Limit, Range and leaderboard now can be adjusted.
Each has 4 states in the following brackets:
0-600 -> Phone view
600-1200 -> Tablet view
1200-1600 ->merged small scren view
1600+ -> big screen view(nothing hidden)

### Link the related issue
Closes #2689

### CODE REVIEW

**Review by benwolski — CHANGES_REQUESTED** [review]
@mishaHype, we seem to have an issue with extra space on the right side of the transaction table on /account.

Apologies if this is the result of one of my updates to your branch!

image

**Review by benwolski — CHANGES_REQUESTED** [review]
@mishaHype / @enwong10, I'm still getting some appearances on the transactions table on /account

https://deploy-preview-2851--ambient-finance.netlify.app/benwolski.eth

image

**Comment by enwong10** [comment]
Should also update the bar on the left for "your" transactions (only when viewing all transactions) to be absolutely positioned so it doesn't shift the entire row to the right

**Review by benwolski — APPROVED** [review]
looking good!

**Pull request merged**
