### PR TITLE
Reposition modal UX changes

### PR DESCRIPTION
**Pull request by surudhb**
### Link the related issue

_Closes #2349 

### Checklist before requesting a review
- [ ] Is this a PR meant for test purposes? If so, please open/change to a draft PR to indicate work in progress/test. 
- [x] I have performed a self-review of my code.
- [x] Did you request feedback from another team member prior to merge? 
- [x] Does my code following the style guide at `docs/CODING-STYLE.md`?

### CODE REVIEW

**Review by benwolski — APPROVED** [review]
changes look good to me!

@miyuki-eto

**Comment by miyuki-eto** [comment]
1. the header text is too large
2. the est. new fields dont update properly. sometimes when initally clicking reposition the dont update at all. if switching between multiple positions to be repositioned it often uses the values from the previous position. resulting in things like this -
image
this flows through to the confirmation modal. its unclear what would happen if i tried to send this through. but it appears as though i will lose a lot of money
3. the confirmation modal has a few issues -
4. the token logos are wrong. 
5. the in range/out of range indicator appears wrong (this MAY have been a design decision im not sure)
image
6. the apr color is incorrect

**Comment by surudhb** [comment]
i definitely misunderstood this ticket as talking about the "reposition modal" as the view that shows up in the module area when you click 'Reposition'. Will update this ticket with the changes mentioned above, tyty for the notes and updates @benwolski @miyuki-eto

**Comment by miyuki-eto** [comment]
> i definitely misunderstood this ticket as talking about the "reposition modal" as the view that shows up in the module area when you click 'Reposition'. Will update this ticket with the changes mentioned above, tyty for the notes and updates @benwolski @miyuki-eto

yeah sorry. it was kinda referring to both. the area in the right side order input section, and also the modal that pops up when submitting the order

**Comment by surudhb** [comment]
changes should be in! 

regarding the bug showing "older" new estimates. the calculation isn't instant which is why it appears to linger on the older value for some time. for now, ive added a `...` placeholder while the new estimate is being calculated

@miyuki-eto lmk any more changes you'd like

**Review by miyuki-eto — COMMENTED** [review]
i like the addition of the `...` while values are being calculated

im still getting the bug with incorrect values.

the rest of the changes look good. 

feel free to merge and shift the bug to a new issue

**Comment by surudhb** [comment]
new issue to capture bug with the inconsistent est. new fields https://github.com/CrocSwap/ambient-ts-app/issues/2528

**Pull request merged**
