### PR TITLE
Update trade table UI

### PR DESCRIPTION
**Pull request by enwong10**
### Describe your changes 

Trade table UI changes 
Fix account page trade table pagination styling 

### Link the related issue

_Closes #2340_

### Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] Did you request feedback from another team member prior to merge? 
- [x] Does my code following the style guide at `docs/CODING-STYLE.md`?

### CODE REVIEW

**Review by benwolski — APPROVED** [review]
changes look great!

**Comment by miyuki-eto** [comment]
1. the buttons nested under the dots menu should have a bg and border that matches the normal ones even when not hovered
image
2. when the table is expanded there is now no padding around it at all. can we make the padding match the table when its not fully expanded? i.e. 16px on all sides
3. im assuming the tiny number formatting is being worked on as a larger issue

**Comment by enwong10** [comment]
> 1. the buttons nested under the dots menu should have a bg and border that matches the normal ones even when not hovered
>    image
> 2. when the table is expanded there is now no padding around it at all. can we make the padding match the table when its not fully expanded? i.e. 16px on all sides
> 3. im assuming the tiny number formatting is being worked on as a larger issue

1. will make those changes
2. this one is tricky because the chart doesnt have a padding, so if the table has a padding then the header starts to move around - one option is to add a 16px padding to the chart 
3. yeeeep

**Comment by miyuki-eto** [comment]
> > 1. the buttons nested under the dots menu should have a bg and border that matches the normal ones even when not hovered
> >    image
> > 2. when the table is expanded there is now no padding around it at all. can we make the padding match the table when its not fully expanded? i.e. 16px on all sides
> > 3. im assuming the tiny number formatting is being worked on as a larger issue
> 
> 1. will make those changes
> 2. this one is tricky because the chart doesnt have a padding, so if the table has a padding then the header starts to move around - one option is to add a 16px padding to the chart
> 3. yeeeep

re 2 - hmm this is unfortunate. basically the issue is when the table is expanded and there is no padding it blurs the lines between the different sections - sidebar/table/order input. this is how the padding is set up in the figma 
image

also i misspoke its actually 8px padding. 

lmk if there is anything we can do or if we have to rethink it. thank you

**Review by miyuki-eto — APPROVED** [review]
looks good! reviewed and approved

**Pull request merged**
