### PR TITLE
Small Number Formatting + Consolidation

### PR DESCRIPTION
**Pull request by enwong10**
### Describe your changes 
Small number formatting + consolidation 

### Link the related issue
_Closes #2491_
_Closes #2537_
_Closes #1569_

### Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] Did I request feedback from a team member prior to merge? 
- [x] Does my code following the style guide at `docs/CODING-STYLE.md`?

### CODE REVIEW

**Review by benwolski — CHANGES_REQUESTED** [review]
@enwong10, I think we should try to avoid abbreviating large token quantities like this: 
image

**Comment by benwolski** [comment]
Similarly, I think we should avoid abbreviating prices that populate input fields using alphabetical characters, unless we add support for accepting user input in this format: 

image

**Review by benwolski — CHANGES_REQUESTED** [review]
@enwong10, seems we have a new bug related to the conversion of commas to periods: 

https://github.com/CrocSwap/ambient-ts-app/assets/570819/83bb2ef5-13bd-4ab0-b9a7-a33cca1acfb4

**Review by benwolski — CHANGES_REQUESTED** [review]
@enwong10, I'm not currently able to type a number like "0.01" in the quantity input field here: 

image

**Comment by benwolski** [comment]
also, I think we're intending to let the user type scientific/exponential notation input in these fields? I'm no longer able to type the letter 'e' or '-'.

**Review by benwolski — CHANGES_REQUESTED** [review]
there appears to be unexpected behavior after modifying a scientific number (video attached demonstrates an attempt to modify 8.22e-10 to 9.22e-10:

https://github.com/CrocSwap/ambient-ts-app/assets/570819/552b1fba-ebf4-46c5-80cf-a11396412f1e

**Review by benwolski — CHANGES_REQUESTED** [review]
A few notes:

1. Token quantity input fields in the exchange balance module do not yet appear to accept exponential notation
2. The cursor jumps to the end of a limit price like 8.37e-10 when attempting to delete the leading digit (8)
3. Some range boundary prices get cut off in non-balanced mode input fields (e.g. 5.59e-10)
image

**Comment by surudhb** [comment]
> A few notes:
> 
> 1. Token quantity input fields in the exchange balance module do not yet appear to accept exponential notation

gonna scope this out to another ticket https://github.com/CrocSwap/ambient-ts-app/issues/2577

**Review by benwolski — CHANGES_REQUESTED** [review]
I can't delete when my cursor is in this position. Nothing happens when I backspace.
image

**Review by benwolski — CHANGES_REQUESTED** [review]
missing current price of pool here:

image

**Comment by surudhb** [comment]
flickering when changing from a "bigger" input to a "smaller" input number

https://github.com/CrocSwap/ambient-ts-app/assets/45405267/a4c4c457-b637-485e-ae20-a997e99ad223

**Review by benwolski — APPROVED** [review]

**Pull request merged**
