### PR TITLE
Update chart tooltips UI

### PR DESCRIPTION
**Pull request by enwong10**
### Describe your changes 

Update chart tooltips UI
### Link the related issue

_Closes #2336_

### Checklist before requesting a review
- [x] I have performed a self-review of my code.
- [x] Did you request feedback from another team member prior to merge? 
- [x] Does my code following the style guide at `docs/CODING-STYLE.md`?

### CODE REVIEW

**Comment by miyuki-eto** [comment]
the full screen and copy chart tooltips appear different from the rest of the app. the text size and color is different from the ones on the right order input panel for instance. the padding looks correct and overall they look better than before, but just a bit inconsistent throughout the app

**Review by benwolski — CHANGES_REQUESTED** [review]
@enwong10, I just noticed that the tooltip shown when the user hovers over the token logos above the chart/table doesn't look as good on the preview as on develop when the pool contains two non-ETH tokens. I'm not sure if the solution is to fix the display, or remove the tooltip. Maybe removing the tooltip and adding the same price inversion click handler to the token logos as the token symbols/price components directly to the right of the logos would be best. 

@miyuki-eto 

image
image

**Comment by enwong10** [comment]
yeah thats definitely an issue - thoughts on what the expected behavior should be: tooltip on hover or invert on click - @miyuki-eto?

**Comment by miyuki-eto** [comment]
yeah lets just remove the tooltip and add the denomination switching behavior to the token logos also. we will soon have the info tab on the table which will display the contract addresses for each token so the hover tooltip wont be so necessary

**Review by benwolski — APPROVED** [review]

**Pull request merged**
